trigger:
- master

pool:
  name: 'Default'

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'demo/pom.xml'
    goals: 'test'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    mavenVersionOption: 'Default'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'demo/target' 
    ArtifactName: 'drop'
    publishLocation: 'Container'

