trigger:
- master  # Trigger the pipeline on commits to the master branch

pool:
  vmImage: 'ubuntu-latest'  # Use the latest Ubuntu virtual machine

jobs:
- job: BuildAndPublish  # Define a single job
  steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'demo/pom.xml'  
      goals: 'package'