trigger:
- master

pool:
  name: 'Default'

steps:
- task: Maven@4
  inputs:
    azureSubscription: 'Free Trial (7a0a02f9-8709-48f8-9bdc-46e63bf41cf5)'
    mavenPomFile: 'demo/pom.xml'
    goals: 'test'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'demo/target' 
    ArtifactName: 'drop'
    publishLocation: 'Container'

