trigger:
- master  # Trigger the pipeline on commits to the master branch

pool:
  vmImage: 'ubuntu-latest'  # Use the latest Ubuntu virtual machine

jobs:
- job: BuildAndPublish  # Define a single job
  steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'demo/pom.xml'  # Path to the Maven POM file
      goals: 'package'  # Maven goal to execute (e.g., package)

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'  # Default working directory
      Contents: '**/target/*.jar'  # Specify the pattern for JAR files
      TargetFolder: '$(Build.ArtifactStagingDirectory)'  # Target directory for copied files

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'  # Path to publish artifacts from
      artifactName: 'drop'  # Name of the published artifact
